### ISSUE TITLE
Branches & Pull Requests

### ISSUE THREAD

**Issue by murillio4** [knowit/Dataplattform-Eventbooks-Frontend#28]
Da dere er flere på samme prosjekt burde dere begynne å bruke branches, og gjøre pull requests når dere skal merge mot master. Er en fin måte å unngå feil på, samt lære av hverandre. Det er også en fin standard å ta med seg videre :)

**Comment by pernillej** [comment]
Vi har brukt branches og pull requests helt siden vi startet. Er for øyeblikket ikke så mange branches og PR's igjen lengre fordi dette er siste dagen vår før vi begynner å jobbe fast i høst.
