### ISSUE TITLE
Service klasser eller moduler

### ISSUE THREAD

**Issue by murillio4** [knowit/Dataplattform-Eventbooks-Frontend#6]
Om dere ønsker å ha servicene deres som klasser istedenfor moduler ville jeg sett på [tsyringe](https://github.com/microsoft/tsyringe). tsyringe er et dependency injection rammeverk for typescript og funker fint i frontend.

Er viktig å holde en konvenson slik at koden ikke blir rotete. Om dere velger klasser, så ville jeg skrevet om `auth.service.ts` til klasse istedenfor modul.

**Comment by choffa** [comment]
Fikset i PR #8, valgte å gå for moduler.
